### ISSUE TITLE
How to Set Additional auto.master options

### ISSUE THREAD

**Issue by benyanke** [cmprescott/ansible-role-autofs#19]
I like to set options like `--ghost` or `--timeout=20` on my master file. How can I accomplish this with this package?

I looked at [this](https://github.com/cmprescott/ansible-role-autofs/blob/1e52d2e57a964345a20ba591bd73f438f2e16576/tasks/main.yml#L43)  and it seems that I could add an 'options' key under 'autofs_indirect_maps`, but this did nothing.

Any thoughts?

**Comment by cmprescott** [comment]
Should be working. Feel free to reach out to developers in https://github.com/cmprescott/ansible-role-autofs/pull/15 or https://github.com/cmprescott/ansible-role-autofs/pull/14

**Comment by benyanke** [comment]
Thanks. I've mentioned them in one of those threads.

**Comment by benyanke** [comment]
Any updates on this one? It still isn't working as advertised...

**Comment by benyanke** [comment]
Found the issue - it's in the repo here, but not released to the ansible galaxy site. @cmprescott can you trigger a new release?

**Comment by cmprescott** [comment]
Oh that's easy! Please check again. 0.4.0 should include what you are looking for.

**Comment by benyanke** [comment]
Worked!
